//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoveSilk.Common.SelectItemHelper {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysConfig() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoveSilk.Common.SelectItemHelper.SysConfig", typeof(SysConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 shiguweizhi 的本地化字符串。
        /// </summary>
        internal static string 事故位置 {
            get {
                return ResourceManager.GetString("事故位置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shiguxingzhi 的本地化字符串。
        /// </summary>
        internal static string 事故性质 {
            get {
                return ResourceManager.GetString("事故性质", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dianfufangshi 的本地化字符串。
        /// </summary>
        internal static string 垫付方式 {
            get {
                return ResourceManager.GetString("垫付方式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kehuxinyong 的本地化字符串。
        /// </summary>
        internal static string 客户信用 {
            get {
                return ResourceManager.GetString("客户信用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kehushuxing 的本地化字符串。
        /// </summary>
        internal static string 客户属性 {
            get {
                return ResourceManager.GetString("客户属性", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kehuxingzhi 的本地化字符串。
        /// </summary>
        internal static string 客户性质 {
            get {
                return ResourceManager.GetString("客户性质", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kehulaiyuan 的本地化字符串。
        /// </summary>
        internal static string 客户来源 {
            get {
                return ResourceManager.GetString("客户来源", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 anjianshuxing 的本地化字符串。
        /// </summary>
        internal static string 案件属性 {
            get {
                return ResourceManager.GetString("案件属性", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 anjianzhuangtai 的本地化字符串。
        /// </summary>
        internal static string 案件状态 {
            get {
                return ResourceManager.GetString("案件状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 anjianleixing 的本地化字符串。
        /// </summary>
        internal static string 案件类型 {
            get {
                return ResourceManager.GetString("案件类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zhiliaofangshi 的本地化字符串。
        /// </summary>
        internal static string 治疗方式 {
            get {
                return ResourceManager.GetString("治疗方式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 keshi 的本地化字符串。
        /// </summary>
        internal static string 科室 {
            get {
                return ResourceManager.GetString("科室", resourceCulture);
            }
        }
    }
}
